linters:
  enable:
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - revive
  - gomnd
  - goprintffuncname
  - gochecknoglobals
  - gochecknoinits
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - rowserrcheck
  - exportloopref
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace

issues:
  exclude-use-default: false