name: CI test

on:
  push:
    branches:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - name: build and test
        run: |
          go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
          go build -race ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
