name: test

on:
  push:
    branches:
    tags:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: test
      run: go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.23.6
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run --enable-all --disable wsl,lll,funlen ./...

