name: test

on:
  push:
    branches:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: test
      run: go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
    - name: install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.50.1
    - name: install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...
    - name: submit coverage
      run: goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
